/**
 * @file        net/rexnet_ffi.h
 * @brief       C ABI of rexnet-core (Rust) — design spec §12.
 *
 * @copyright   Copyright (c) 2026 Ryan Fisher <ryanfisher099@gmail.com>
 *              All rights reserved.
 *
 * @license     BSD 3-Clause License
 *              See LICENSE file in the project root for full license text.
 *
 * GENERATED by cbindgen from src/rexnet/core/src/ffi.rs (see
 * core/cbindgen.toml and core/build.rs). Do not edit by hand.
 * Non-blocking command-in / poll-event-out: the library owns its tokio
 * runtime and the game thread never blocks.
 */

#pragma once

#include <stdbool.h>
#include <stdint.h>

/**
 * Level ordinals handed to the sink. Deliberately explicit rather than
 * mirroring `tracing::Level`'s internal ordering.
 */
#define REXNET_LOG_ERROR 0

#define REXNET_LOG_WARN 1

#define REXNET_LOG_INFO 2

#define REXNET_LOG_DEBUG 3

#define REXNET_LOG_TRACE 4

/**
 * Largest datagram payload deliverable in one event (fits standard MTU).
 */
#define REXNET_EVENT_DATA_MAX 1472

#define REXNET_EVENT_NONE 0

#define REXNET_EVENT_PEER_CONNECTED 1

#define REXNET_EVENT_PEER_DISCONNECTED 2

#define REXNET_EVENT_PRESENCE_UPDATED 3

#define REXNET_EVENT_FRIEND_REQUEST 4

#define REXNET_EVENT_FRIEND_ACCEPTED 5

#define REXNET_EVENT_INVITE_RECEIVED 6

#define REXNET_EVENT_INVITE_REPLIED 7

#define REXNET_EVENT_PUNCH_RESULT 8

#define REXNET_EVENT_SESSION_FOUND 9

#define REXNET_EVENT_DATAGRAM 10

/**
 * Punch failed; traffic for `peer` rides the control tunnel (degraded).
 */
#define REXNET_EVENT_DEGRADED 11

#define REXNET_EVENT_ERROR 12

#define REXNET_EVENT_FRIEND_REMOVED 13

/**
 * Ambient shard presence (§17.3.4). Append-only: the C header mirrors
 * this ordering, so never insert above an existing variant.
 */
#define REXNET_EVENT_SHARD_PRESENCE 14

/**
 * A peer started/stopped relaying our traffic (§17.2); flag = is_relay.
 */
#define REXNET_EVENT_RELAY_STATUS 15

/**
 * Our own virtual address changed (§17.3.5); virtual_ip carries it.
 */
#define REXNET_EVENT_LOCAL_ADDRESS 16

/**
 * Guest TCP connection opened (§18). virtual_ip = peer, port =
 * local guest port, src_port = remote guest port, flag = 1 when we
 * opened it. data = 8-byte big-endian stream id.
 */
#define REXNET_EVENT_STREAM_OPENED 17

/**
 * Bytes on a guest TCP connection. data = [stream id 8][payload].
 */
#define REXNET_EVENT_STREAM_DATA 18

/**
 * Guest TCP connection ended. data = 8-byte stream id.
 */
#define REXNET_EVENT_STREAM_CLOSED 19

/**
 * Outbound guest TCP connect failed. virtual_ip = peer, port = dst.
 */
#define REXNET_EVENT_STREAM_CONNECT_FAILED 20

/**
 * Measured round trip to a peer. virtual_ip = peer, port = milliseconds.
 */
#define REXNET_EVENT_PEER_RTT 21

/**
 * A directly dialable public endpoint for us was confirmed (UPnP/AutoNAT).
 * data = UTF-8 bare `host:port` to hand a peer for a direct connect.
 */
#define REXNET_EVENT_EXTERNAL_ADDRESS 22

typedef struct RexNetHandle RexNetHandle;

typedef struct RexNetConfig {
  /**
   * Directory holding `identity.key` and friend/session state. UTF-8.
   */
  const char *data_dir;
  /**
   * Title id derived by the shim from the XEX execution-info header (§11.0).
   */
  uint32_t title_id;
  /**
   * Self-asserted display name, UTF-8, <= 32 bytes.
   */
  const char *display_name;
  /**
   * Bootstrap multiaddrs; empty list is valid (LAN/manual/v6 still work).
   */
  const char *const *bootstrap;
  uint32_t bootstrap_len;
  /**
   * Circuit-v2 relays to hold reservations on (§9). Accelerant, never
   * authority: empty is supported and a dead entry costs only speed.
   */
  const char *const *relays;
  uint32_t relays_len;
  /**
   * Also merge in [`crate::AMINO_BOOTSTRAP`] (the standard public set).
   */
  bool use_default_bootstrap;
  /**
   * Skip hole punching; carry game traffic over the control tunnel (§14).
   * Lets a developer reproduce a CGNAT player's degraded path on a LAN,
   * where every punch would otherwise succeed.
   */
  bool force_tunnel;
  /**
   * Fixed control-plane (QUIC/TCP) listen port; 0 = ephemeral. A stable
   * port is what makes a UPnP mapping or a manual forward reusable across
   * launches, so the address a peer pastes stays valid.
   */
  uint16_t listen_port;
  /**
   * Fixed game-plane UDP port; 0 = ephemeral.
   */
  uint16_t game_port;
} RexNetConfig;

/**
 * Multihash-encoded PeerId, length-prefixed (ed25519 identity hashes fit
 * well under 64 bytes).
 */
typedef struct RexNetPeerId {
  uint8_t len;
  uint8_t bytes[63];
} RexNetPeerId;

/**
 * Fixed-size POD event, drained once per frame via [`rexnet_poll_event`].
 * Variable payloads (presence records, session descriptors, datagrams,
 * error text) are carried in `data`/`data_len`, encoded per §8.
 */
typedef struct RexNetEvent {
  /**
   * One of the `REXNET_EVENT_*` values.
   */
  uint32_t kind;
  struct RexNetPeerId peer;
  /**
   * PeerConnected: the peer's allocated 10.77.0.0/16 address.
   * Datagram: the sender's virtual IP.
   */
  uint32_t virtual_ip;
  /**
   * Datagram: guest destination port.
   */
  uint16_t port;
  /**
   * Datagram: guest source port (for reply routing).
   */
  uint16_t src_port;
  uint8_t flag;
  uint8_t _pad;
  uint32_t data_len;
  uint8_t data[REXNET_EVENT_DATA_MAX];
} RexNetEvent;

/**
 * `extern "C" fn(level, nul-terminated message)`. The message borrows only
 * for the duration of the call.
 */
typedef void (*RexNetLogSink)(uint32_t, const char*);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Route rexnet-core's `tracing` output to `sink`. Safe to call more than
 * once (the subscriber installs once; the sink is swapped). Pass `None` to
 * silence. Verbosity follows `REXNET_LOG` (default `info`).
 *
 * # Safety
 * `sink` must be callable from any thread for the process lifetime, since
 * the engine logs from its own tokio threads.
 */
void rexnet_set_log_sink(void (*sink)(uint32_t, const char*));

/**
 * # Safety
 * `cfg` must point to a valid [`RexNetConfig`] with valid, NUL-terminated
 * strings. Returns null on failure.
 */
struct RexNetHandle *rexnet_init(const struct RexNetConfig *cfg);

/**
 * # Safety
 * `handle` must come from [`rexnet_init`] and not be used afterwards.
 */
void rexnet_shutdown(struct RexNetHandle *handle);

/**
 * Block the calling thread until an event is queued or `timeout_ms`
 * elapses. Returns true if woken by an event. A wake with an empty queue is
 * possible (the event was drained by another poll) and harmless.
 *
 * This is what lets the shim's pump thread deliver a datagram the moment
 * it arrives rather than on its next fixed tick.
 *
 * # Safety
 * `handle` from [`rexnet_init`], not yet shut down.
 */
bool rexnet_wait_event(struct RexNetHandle *handle, uint32_t timeout_ms);

/**
 * # Safety
 * `handle` from [`rexnet_init`]; `out` must point to a [`RexNetEvent`].
 * Returns true while events remain; drain once per frame.
 */
bool rexnet_poll_event(struct RexNetHandle *handle, struct RexNetEvent *out);

/**
 * Render a peer id as its canonical base58 string into `out` (NUL
 * terminated, truncated to `cap`). Returns the number of bytes written
 * (excluding NUL), or 0 on failure.
 *
 * # Safety
 * `peer` points to a valid [`RexNetPeerId`]; `out` has room for `cap` bytes.
 */
uint32_t rexnet_peer_id_string(const struct RexNetPeerId *peer, char *out, uint32_t cap);

/**
 * Parse a peer identity into `out`: accepts either the canonical base58
 * peer-id string or a `REXN-…` friend code (case-insensitive, dashes
 * optional). Returns false on malformed input (or a multihash exceeding
 * the fixed 63-byte capacity — never the case for standard ed25519 ids).
 *
 * # Safety
 * `s` is a NUL-terminated string; `out` points to a [`RexNetPeerId`].
 */
bool rexnet_peer_id_parse(const char *s, struct RexNetPeerId *out);

/**
 * Render a peer id (+ optional display name, NUL-terminated UTF-8, ≤24
 * bytes used) as a `REXN-…` friend code into `out` (NUL-terminated).
 * Returns bytes written (excluding NUL), or 0 if the peer id is not an
 * ed25519 identity (or `cap` is too small — codes are ≤119 chars + NUL).
 *
 * # Safety
 * `peer` points to a valid [`RexNetPeerId`]; `name` is NULL or a
 * NUL-terminated string; `out` has room for `cap` bytes.
 */
uint32_t rexnet_friend_code(const struct RexNetPeerId *peer,
                            const char *name,
                            char *out,
                            uint32_t cap);

/**
 * Parse a friend code, returning the peer id and the embedded display
 * name ("" for nameless codes) — `name_out` may be NULL to skip the name.
 * Returns false on malformed input (checksum mismatches included).
 *
 * # Safety
 * `s` is NUL-terminated; `out_peer` points to a [`RexNetPeerId`];
 * `name_out` is NULL or has room for `name_cap` bytes.
 */
bool rexnet_friend_code_parse(const char *s,
                              struct RexNetPeerId *out_peer,
                              char *name_out,
                              uint32_t name_cap);

/**
 * Change the self-asserted display name at runtime; presence is re-pushed
 * to friends immediately. The name is sanitized (control chars stripped,
 * truncated to 24 bytes on a char boundary).
 *
 * # Safety
 * `handle` from [`rexnet_init`]; `name` is a NUL-terminated string.
 */
void rexnet_set_display_name(struct RexNetHandle *handle, const char *name);

/**
 * # Safety
 * `handle` from [`rexnet_init`]; `out` must point to a [`RexNetPeerId`].
 */
void rexnet_local_peer_id(struct RexNetHandle *handle, struct RexNetPeerId *out);

/**
 * # Safety
 * `handle` from [`rexnet_init`]; `presence`/`presence_len` describe a
 * postcard-encoded presence payload (§8.1) owned by the caller.
 */
void rexnet_set_presence(struct RexNetHandle *handle,
                         uint32_t title_id,
                         uint8_t state,
                         const uint8_t *presence,
                         uint32_t presence_len);

/**
 * # Safety
 * `handle` from [`rexnet_init`]; `peer` must point to a valid [`RexNetPeerId`].
 * Fire-and-forget game-plane punch (§8.4); the outcome arrives as a
 * `PunchResult` event.
 */
void rexnet_punch_peer(struct RexNetHandle *handle, const struct RexNetPeerId *peer);

/**
 * # Safety
 * `handle` from [`rexnet_init`]; `peer` must point to a valid [`RexNetPeerId`].
 */
void rexnet_connect_peer(struct RexNetHandle *handle, const struct RexNetPeerId *peer);

/**
 * # Safety
 * `handle` from [`rexnet_init`]; `multiaddr` is a NUL-terminated string
 * (manual connect string, the preservation floor — §4).
 */
void rexnet_connect_manual(struct RexNetHandle *handle, const char *multiaddr);

/**
 * # Safety
 * `handle` from [`rexnet_init`]; `peer` valid. Invites `peer` to the
 * current local session (§8.3); the reply arrives as an InviteReplied
 * event, and an accepting invitee fetches our session descriptor.
 */
void rexnet_send_invite(struct RexNetHandle *handle, const struct RexNetPeerId *peer);

/**
 * # Safety
 * `handle` from [`rexnet_init`]; `peer` valid. Accepting also fetches the
 * host's session descriptor (arrives as a SessionFound event).
 */
void rexnet_invite_reply(struct RexNetHandle *handle, const struct RexNetPeerId *peer, bool accept);

/**
 * # Safety
 * `handle` from [`rexnet_init`]; `peer` valid; `note` NUL-terminated.
 */
void rexnet_friend_request(struct RexNetHandle *handle,
                           const struct RexNetPeerId *peer,
                           const char *note);

/**
 * # Safety
 * `handle` from [`rexnet_init`]; `peer` valid.
 */
void rexnet_friend_accept(struct RexNetHandle *handle, const struct RexNetPeerId *peer);

/**
 * # Safety
 * `handle` from [`rexnet_init`]; `peer` valid.
 */
void rexnet_friend_remove(struct RexNetHandle *handle, const struct RexNetPeerId *peer);

/**
 * # Safety
 * `handle` from [`rexnet_init`]; `session_id` must point to 16 bytes
 * (allocated by the shim; surfaced to the guest as XNKID+XNKEY).
 */
void rexnet_session_create(struct RexNetHandle *handle,
                           const uint8_t *session_id,
                           uint8_t slots_total,
                           uint8_t slots_open,
                           bool is_public);

/**
 * # Safety
 * `handle` from [`rexnet_init`].
 */
void rexnet_session_delete(struct RexNetHandle *handle);

/**
 * Guest TCP connect to a peer's virtual IP (§18). Result arrives as a
 * StreamOpened or StreamConnectFailed event.
 *
 * # Safety
 * `handle` from [`rexnet_init`].
 */
void rexnet_stream_connect(struct RexNetHandle *handle,
                           uint32_t virtual_ip,
                           uint16_t src_port,
                           uint16_t dst_port);

/**
 * Write to a guest TCP connection.
 *
 * # Safety
 * `handle` from [`rexnet_init`]; `data` must be readable for `len` bytes.
 */
void rexnet_stream_send(struct RexNetHandle *handle,
                        uint64_t stream_id,
                        const uint8_t *data,
                        uint32_t len);

/**
 * Close a guest TCP connection.
 *
 * # Safety
 * `handle` from [`rexnet_init`].
 */
void rexnet_stream_close(struct RexNetHandle *handle, uint64_t stream_id);

/**
 * Opt in to the ambient title shard (§17.3). Idempotent; `cap` of 0 takes
 * the spec default of 255. Titles opt in via `rexnet.toml` (§17.5) -- this
 * is never implied, so a game that has no use for ambient presence pays no
 * traffic for it.
 *
 * # Safety
 * `handle` from [`rexnet_init`].
 */
void rexnet_shard_enable(struct RexNetHandle *handle, uint16_t cap);

/**
 * Leave any shard and stop publishing/scanning.
 *
 * # Safety
 * `handle` from [`rexnet_init`].
 */
void rexnet_shard_disable(struct RexNetHandle *handle);

/**
 * # Safety
 * `handle` from [`rexnet_init`]. Results arrive as SessionFound events
 * (peer = host, data = 16-byte session id, port/src_port = total/open
 * slots, flag = requires_invite). Filtering on game-defined attributes is
 * applied client-side by the shim per the game config.
 */
void rexnet_session_search(struct RexNetHandle *handle);

/**
 * # Safety
 * `handle` from [`rexnet_init`]; `data`/`len` owned by the caller.
 *
 * `src_port`/`dst_port` are the guest ports (the game socket multiplexes
 * all of them). `reliable` exists for module-internal traffic only. Guest
 * datagrams MUST pass false when the game config sets
 * `game_channel = "unreliable"` (own-reliability titles like XRNM — §6).
 */
void rexnet_send_datagram(struct RexNetHandle *handle,
                          uint32_t virtual_ip,
                          uint16_t src_port,
                          uint16_t dst_port,
                          const uint8_t *data,
                          uint32_t len,
                          bool reliable);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
